#add user details for the different user test cases
#Tester1Name=BGuser1
#Tester1Password=user@123
#Tester2Name=BGuser2
#Tester2Password=BGuser@123
# Explain in the readme file what is done in this file and the implementation 
